import {
  Radio,
  Heart,
  TrendingUp,
  TrendingDown,
  Globe,
  MapPin,
  Inbox,
  PhoneCall,
  Star,
  Eye,
  Search,
  Navigation,
  MousePointerClick,
  MousePointer2,
  MessageSquare,
  UserPlus,
  FileText,
  Clock,
  ClipboardCheck,
  Download,
  Package,
  MessageCircle,
  Mail,
  Percent,
  Linkedin,
  Instagram,
  Youtube,
  Facebook,
  Twitter,
  Music2,
  LayoutDashboard,
  Share2,
  MapPinned,
  Monitor,
  Target,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps the icon-name strings used in mockData.ts (and the sidebar) to concrete
 * lucide-react components. Centralizing this keeps the data layer free of JSX
 * and avoids shipping the entire icon set to the client.
 */
const ICONS: Record<string, LucideIcon> = {
  Radio,
  Heart,
  TrendingUp,
  TrendingDown,
  Globe,
  MapPin,
  Inbox,
  PhoneCall,
  Star,
  Eye,
  Search,
  Navigation,
  MousePointerClick,
  MousePointer2,
  MessageSquare,
  UserPlus,
  FileText,
  Clock,
  ClipboardCheck,
  Download,
  Package,
  MessageCircle,
  Mail,
  Percent,
  Linkedin,
  Instagram,
  Youtube,
  Facebook,
  Twitter,
  Music2,
  LayoutDashboard,
  Share2,
  MapPinned,
  Monitor,
  Target,
};

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Target;
}
