"""Regenerate scripts/product_order.txt from the catalog.

The order file drives the prev/next arrows on every product page. It is derived
from the order cards appear in products.html, so reordering the catalog and
re-running this keeps the arrows in step.

    python3 scripts/gen_product_order.py            # write the file
    python3 scripts/gen_product_order.py --check    # exit 1 if out of date
"""

import sys

from nlc_catalog import CatalogError, catalog_path, ordered_keys, parse_catalog, site_root

HEADER = (
    '# Product browse order — generated by scripts/gen_product_order.py\n'
    '# Source of truth is the card order in products.html. Do not hand-edit:\n'
    '# reorder the catalog instead, then re-run the generator.\n'
)


def build_order(root):
    return ordered_keys(parse_catalog(catalog_path(root, 'en')))


def main(argv):
    check_only = '--check' in argv
    root = site_root()
    keys = build_order(root)
    target = root / 'scripts' / 'product_order.txt'
    contents = HEADER + '\n'.join(keys) + '\n'

    if check_only:
        current = target.read_text(encoding='utf-8') if target.is_file() else ''
        if current != contents:
            print('product_order.txt is out of date — run scripts/gen_product_order.py')
            return 1
        print('product_order.txt is up to date (%d products).' % len(keys))
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(contents, encoding='utf-8')
    print('Wrote %s (%d products).' % (target.relative_to(root), len(keys)))
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1:]))
    except CatalogError as exc:
        print('error: %s' % exc, file=sys.stderr)
        sys.exit(2)
