"""Inject or refresh the floating prev/next arrows on every product page.

The arrows follow scripts/product_order.txt and wrap around, so the last
product leads back to the first. Run this after adding, removing or reordering
products.

The injected block is wrapped in HTML comment markers, so re-running replaces
the previous block instead of stacking a second set of arrows.

    python3 scripts/inject_prev_next.py              # preview, writes nothing
    python3 scripts/inject_prev_next.py --write      # apply
    python3 scripts/inject_prev_next.py --write --lang en

Pages that already carry arrows from an older script will not have the markers.
Point LEGACY_BLOCK_RE at that older markup and it gets replaced in place;
otherwise those pages are reported as needing a look rather than being given a
second set of arrows.
"""

import re
import sys

from nlc_catalog import (
    CatalogError,
    all_cards,
    catalog_path,
    parse_catalog,
    product_page,
    read_order_file,
    site_root,
)

START = '<!-- nlc:prev-next start (generated by scripts/inject_prev_next.py) -->'
END = '<!-- nlc:prev-next end -->'

# Arrow markup produced by an earlier version of this tooling. Anything
# matching is replaced rather than duplicated. Widen this if older pages use
# different markup.
LEGACY_BLOCK_RE = re.compile(
    r'\s*<(?:nav|div)[^>]*class="[^"]*\b(?:pd-nav|pd-arrows|prod-nav-arrows)\b[^"]*"[^>]*>'
    r'.*?</(?:nav|div)>',
    re.S,
)

# Positioned with logical properties so the arrows swap sides automatically on
# the RTL pages; only the chevron glyphs need picking per language.
STYLE = """<style>
.pd-nav{position:fixed;inset-block-start:50%;inset-inline:0;transform:translateY(-50%);
  display:flex;justify-content:space-between;pointer-events:none;z-index:40;padding:0 12px}
.pd-nav a{pointer-events:auto;display:flex;align-items:center;gap:10px;max-width:44vw;
  padding:12px 18px;border-radius:999px;background:rgba(255,255,255,.92);color:var(--primary,#24285e);
  border:1px solid var(--border,#e2e1e1);box-shadow:0 6px 24px rgba(26,28,58,.12);
  text-decoration:none;font-size:.9rem;line-height:1;backdrop-filter:blur(6px);
  transition:background .2s ease,color .2s ease,transform .2s ease}
.pd-nav a:hover{background:var(--secondary,#F6851F);color:#fff;transform:translateY(-1px)}
.pd-nav .pd-nav-label{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
@media(max-width:768px){.pd-nav .pd-nav-label{display:none}.pd-nav a{padding:12px}}
@media(prefers-reduced-motion:reduce){.pd-nav a{transition:none}}
</style>"""

LABELS = {
    'en': ('Previous', 'Next', 'fa-chevron-left', 'fa-chevron-right'),
    'ar': ('السابق', 'التالي', 'fa-chevron-right', 'fa-chevron-left'),
}


def build_block(prev_key, prev_name, next_key, next_name, lang):
    prev_label, next_label, prev_icon, next_icon = LABELS[lang]
    aria = 'تصفح المنتجات' if lang == 'ar' else 'Product navigation'
    return (
        '%s\n%s\n<nav class="pd-nav" aria-label="%s">\n'
        '  <a href="%s.html" rel="prev" title="%s"><i class="fas %s" aria-hidden="true"></i>'
        '<span class="pd-nav-label">%s</span></a>\n'
        '  <a href="%s.html" rel="next" title="%s"><span class="pd-nav-label">%s</span>'
        '<i class="fas %s" aria-hidden="true"></i></a>\n'
        '</nav>\n%s'
        % (START, STYLE, aria,
           prev_key, prev_label, prev_icon, prev_name,
           next_key, next_label, next_name, next_icon, END)
    )


def names_for(root, lang):
    """Display name per product key, falling back to the English catalog."""
    catalog = catalog_path(root, lang)
    if not catalog.is_file():
        catalog = catalog_path(root, 'en')
    return {c.key: c.name for c in all_cards(parse_catalog(catalog))}


def apply_to_page(path, block):
    """Return (new_html, status) without touching disk."""
    html = path.read_text(encoding='utf-8')

    if START in html and END in html:
        updated = re.sub(re.escape(START) + '.*?' + re.escape(END), lambda _: block,
                         html, count=1, flags=re.S)
        return updated, ('unchanged' if updated == html else 'refreshed')

    legacy = LEGACY_BLOCK_RE.search(html)
    if legacy:
        return html[:legacy.start()] + '\n' + block + html[legacy.end():], 'replaced-legacy'

    if '</body>' not in html:
        return html, 'no-body-tag'

    index = html.rindex('</body>')
    return html[:index] + block + '\n' + html[index:], 'inserted'


def run(root, langs, write):
    order = read_order_file(root)
    if len(order) < 2:
        raise CatalogError('Need at least two products to build prev/next links.')

    counts = {}
    for lang in langs:
        directory = product_page(root, 'x', lang).parent
        if not directory.is_dir():
            print('skip %s: %s not present' % (lang, directory))
            continue

        names = names_for(root, lang)
        for i, key in enumerate(order):
            path = product_page(root, key, lang)
            if not path.is_file():
                counts['missing-page'] = counts.get('missing-page', 0) + 1
                print('  missing %s' % path.relative_to(root))
                continue

            prev_key = order[i - 1]
            next_key = order[(i + 1) % len(order)]
            block = build_block(prev_key, names.get(prev_key, prev_key.upper()),
                                next_key, names.get(next_key, next_key.upper()), lang)
            updated, status = apply_to_page(path, block)
            counts[status] = counts.get(status, 0) + 1
            if status == 'no-body-tag':
                print('  no </body> in %s — skipped' % path.relative_to(root))
            elif write and updated != path.read_text(encoding='utf-8'):
                path.write_text(updated, encoding='utf-8')

    print('\n%s' % ('Applied:' if write else 'Would apply (dry run):'))
    for status in sorted(counts):
        print('  %-16s %d' % (status, counts[status]))
    if not write and counts:
        print('\nRe-run with --write to apply.')
    return 0


if __name__ == '__main__':
    argv = sys.argv[1:]
    selected = ['en', 'ar']
    if '--lang' in argv:
        selected = [argv[argv.index('--lang') + 1]]
    try:
        sys.exit(run(site_root(), selected, write='--write' in argv))
    except CatalogError as exc:
        print('error: %s' % exc, file=sys.stderr)
        sys.exit(2)
